Stat svc
Yabrov/java-explore-with-me pull request #3
Opened 2023-04-15 08:19 UTC by Yabrov

2023-04-15 08:23 UTC, Yabrov commented
Привет! Закончил часть stats-server. Учитывая, что в нем нет сложных сущностей и отношений, то использовал JDBC.

2023-04-15 11:37 UTC, Donald522 requested changes
Привет!

Похоже, что забыл клиента дописать)
В остальном все нормально.

2023-04-15 11:37 UTC, Donald522 commented on main-server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:shareit
Это что-то из прошлой работы осталось видимо)

2023-04-15 11:37 UTC, Donald522 commented on stats/stats-server/pom.xml
> +            <groupId>com.h2database</groupId>
А зачем h2 здесь?

2023-04-15 11:37 UTC, Donald522 commented on stats/stats-server/src/main/java/ru/practicum/stats/server/service/StatsHistoryServiceImpl.java
> +            history.addAll(uniqueIPsOnly.equals(Boolean.TRUE)
А зачем такие сложности с Boolean?)
Почему не примитив и написать
```
uniqueIPsOnly 
  ? ...
  : ...
```

2023-04-15 11:37 UTC, Donald522 commented on stats/stats-client/pom.xml
> +        <artifactId>stats</artifactId>
А где сам клиент?)

2023-04-15 14:16 UTC, Yabrov commented on stats/stats-server/src/main/java/ru/practicum/stats/server/service/StatsHistoryServiceImpl.java
> +            history.addAll(uniqueIPsOnly.equals(Boolean.TRUE)
Это плагин SonarList так советует, переделаю

2023-04-15 14:17 UTC, Yabrov commented on stats/stats-server/pom.xml
> +            <groupId>com.h2database</groupId>
чтобы в идее позапускать тесты постмана, подебажить

2023-04-15 14:18 UTC, Yabrov commented on stats/stats-client/pom.xml
> +        <artifactId>stats</artifactId>
Ааа, затупил, думал он в следующей части, сделаю)

2023-04-15 21:26 UTC, Yabrov commented
Все подправил, сделал клиент.

2023-04-16 19:26 UTC, Donald522 approved these changes
Привет!

Все норм, принимается.

2023-04-16 19:26 UTC, Donald522 commented on stats/stats-client/src/main/java/ru/practicum/stats/client/service/StatsServerClientImpl.java
> +            return objectMapper.convertValue(response.getBody(), new TypeReference<>() {
Тут нельзя написать
`objectMapper.convertValue(response.getBody(), EndpointHitDto::class)`? Не очень понял зачем тут TypeReference, тем более с пустым типом

2023-04-16 19:26 UTC, Donald522 commented on stats/stats-client/src/main/java/ru/practicum/stats/client/service/StatsServerClientImpl.java
> +            String mes = "Unable to save hit";
Тут сообщение не то)

2023-04-16 19:27 UTC, Donald522 commented on stats/stats-server/pom.xml
> +            <groupId>com.h2database</groupId>
h2 может сильно отличаться от постгреса, поэтому я бы советовал для такого просто локально постгрес поднять

2023-04-17 05:07 UTC, merged