Main svc
Yabrov/java-explore-with-me pull request #4
Opened 2023-04-28 15:38 UTC by Yabrov

2023-04-29 10:38 UTC, Yabrov commented
Привет! Доделал основную часть. Взаимодействие с сервером статистики вынес в аспект и сделал асинхронным.

2023-04-30 20:02 UTC, Donald522 requested changes
Привет!

Все отлично, только не очень понравилось, что за статистикой мы ходим из класса маппера. Это нарушает single responsibility принцип - маппер это конвертер, его задача переложить данные из одного объекта в другой, а сбор данные из сети - это не его дело.

2023-05-01 06:47 UTC, Yabrov commented
Все учел, вынес в аспект логику получения кол-во просмотров.

2023-05-02 08:25 UTC, VladimirTitov4 commented on main-server/src/main/java/ru/practicum/main/server/service/category/CategoryServiceImpl.java
> +    @Transactional
При создании транзационность точно не нужна. Транзакционность важна тогда, когда 2 или более потока одновременно обращаются к хранилищу данных и читают оттуда информацию, так вот один поток мог уже изменить сущность, а второй работает ещё с неизмененными данными.
Т.е. транзакционность важна только на чтение

2023-05-02 08:25 UTC, VladimirTitov4 commented on main-server/src/main/java/ru/practicum/main/server/service/category/CategoryServiceImpl.java
> +    public void deleteCategory(Long categoryId) {
В jpa метода deleteById уже стоит транзакционность, думаю здесь дополнительно не нужно ставить Transactional

2023-05-02 08:25 UTC, VladimirTitov4 commented on main-server/src/main/java/ru/practicum/main/server/service/event/EventServiceImpl.java
> +        if (request.getAnnotation() != null) {
В целом чтобы избежать столько строк кода существует библиотека MapStruct, не пробовали подключить ? Достаточно удобная штука

2023-05-02 09:47 UTC, Yabrov commented on main-server/src/main/java/ru/practicum/main/server/model/entities/Category.java
> +    public Category(Long id, String name) {
Дело в том, что аннотация ломбока @AllArgsConstructor игнорирует поле id из класса родителя. А мне нужно, чтобы это поле было в конструкторе.

2023-05-02 09:47 UTC, Yabrov commented on main-server/src/main/java/ru/practicum/main/server/model/entities/Event.java
> +    @OneToMany(mappedBy = "event", fetch = FetchType.EAGER)
Да, обязательно, потому что  эта коллекция подставляется абсолютно при каждой выборке евентов

2023-05-02 10:01 UTC, Yabrov commented on main-server/src/main/java/ru/practicum/main/server/model/entities/User.java
> +    @OneToMany(mappedBy = "initiator", fetch = FetchType.LAZY)
Исправлю

2023-05-02 10:32 UTC, Yabrov commented
Исправил по замечаниям

2023-05-02 20:55 UTC, VladimirTitov4 commented on main-server/src/main/java/ru/practicum/main/server/model/entities/Event.java
> +    @OneToMany(mappedBy = "event", fetch = FetchType.EAGER)
Эта коллекция подставляется только в тех кейсах, которые есть на данный момент в тестах. 
Но при развитии проекта могут появится варианты, в которых нужно будет получить пару полей или что-то вроде того. А эта коллекция так и будет выгружаться вместе с 2мя полями

2023-05-03 14:42 UTC, merged